# This is a basic workflow to help you get started with Actions

name: "go: build versioned binaries"

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-release-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64, arm, arm64]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Go Release Binaries Normal Volume Size
        uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          asset_name: "${{ matrix.goos }}_${{ matrix.goarch }}"
          goversion: "1.17"
          binary_name: "cronitor"
          sha256sum: true
          overwrite: true
